### ISSUE TITLE
Typescript?

### ISSUE THREAD

**Issue by eroblaze** [Voxellius/Voxel#4]
Hello @James-Livesey, I saw your videos on YouTube and I must say this is great!
Is there a reason you chose JavaScript over Typescript for your source code?

**Comment by James-Livesey** [comment]
Hi! For the compiler, I chose to write it in JavaScript as eventually I'm hoping to rewrite it all in Voxel anyway, so it's only a temporary bit of code.

In terms of syntax, Voxel itself is closer to JavaScript than TypeScript,and that's to keep the compiler code small, since static type checking is not needed. I am trying to keep the compiler code small as I would like to try and get the compiler running on an ESP32 so that development can be done on the ESP32 itself if one desires. I might later on add static type checking to Voxel and make it an optional compiler feature as I know it has its uses!

Closing this since I think it answered your question, but let me know if you need clarification or have follow-up questions. For more in-depth discussions, I'd recommend joining [our new Discord server](https://discord.gg/3psbDF6Fv4) as it's a bit more immediate than through GH Issues.
